# Generated by Django 2.2.3 on 2020-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpid', models.CharField(max_length=128, verbose_name='corpid')),
                ('appsecret', models.CharField(max_length=256, verbose_name='APPSECRET')),
                ('expires_in', models.DateTimeField(verbose_name='expires_in')),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='token')),
            ],
            options={
                'verbose_name': '企业微信access_token信息',
                'verbose_name_plural': '企业微信access_token信息',
            },
        ),
    ]
