# Generated by Django 2.2.3 on 2020-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeChatWorkTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='appid',
            field=models.CharField(default='', max_length=128, verbose_name='appid'),
            preserve_default=False,
        ),
    ]
